services:
  app:
    build: .
    container_name: todo_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      - CI_ENVIRONMENT=development
      - database.default.hostname=db
      - database.default.database=todo_ci
      - database.default.username=root
      - database.default.password=root
      - database.default.DBDriver=MySQLi

  db:
    image: mysql:8.0
    container_name: todo_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_ci
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
